import { NexusPageHeader } from "@/components/NexusPageHeader";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { trpc } from "@/lib/trpc";
import { toast } from "sonner";
import { FolderKanban, Loader2, LockKeyhole, Plus, UsersRound } from "lucide-react";
import { useState } from "react";

export default function Collections() {
  const workspace = trpc.nexus.workspace.useQuery();
  const utils = trpc.useUtils();
  const [name, setName] = useState("");
  const [open, setOpen] = useState(false);
  const create = trpc.nexus.createCollection.useMutation({ onSuccess: () => { toast.success("Collection created"); utils.nexus.workspace.invalidate(); setName(""); setOpen(false); }, onError: (error) => toast.error(error.message) });
  const createCollection = () => { const orgId = workspace.data?.organization.id; if (!orgId || !name.trim()) return; create.mutate({ orgId, name: name.trim() }); };
  const collections = workspace.data?.collections ?? [];
  const sources = workspace.data?.sources ?? [];
  return (
    <div className="mx-auto max-w-[1440px]"><NexusPageHeader eyebrow="Scope before retrieval" title="Collections" description="Collections are the access boundary between a workspace, its sources, and the people who can query them." actions={<Dialog open={open} onOpenChange={setOpen}><DialogTrigger asChild><Button className="h-10 bg-cyan-300 font-semibold text-slate-950 hover:bg-cyan-200"><Plus className="mr-2 size-4" /> New collection</Button></DialogTrigger><DialogContent className="border-white/10 bg-[#0b172a] text-slate-100"><DialogHeader><DialogTitle>Create a collection</DialogTitle></DialogHeader><div className="space-y-4 pt-2"><Input value={name} onChange={(event) => setName(event.target.value)} onKeyDown={(event) => { if (event.key === "Enter") createCollection(); }} placeholder="e.g. Engineering handbook" className="border-white/10 bg-white/[0.03] text-white placeholder:text-slate-600" /><p className="text-xs leading-5 text-slate-500">Membership and collection grants determine which evidence can ever enter a query.</p><div className="flex justify-end"><Button onClick={createCollection} disabled={!name.trim() || create.isPending} className="bg-cyan-300 font-semibold text-slate-950 hover:bg-cyan-200">{create.isPending ? <Loader2 className="size-4 animate-spin" /> : "Create collection"}</Button></div></div></DialogContent></Dialog>} />
      <div className="grid gap-4 lg:grid-cols-3"><div className="nexus-panel rounded-3xl p-5 lg:col-span-2"><div className="flex items-start gap-4"><div className="grid size-10 shrink-0 place-items-center rounded-xl bg-cyan-300/10"><FolderKanban className="size-5 text-cyan-300" /></div><div><p className="text-sm font-semibold text-white">Organize knowledge with an explicit scope</p><p className="mt-2 max-w-xl text-sm leading-6 text-slate-500">NEXUS evaluates collection access before candidate retrieval. A source outside an approved collection is never searched.</p></div></div></div><div className="rounded-3xl border border-emerald-300/10 bg-emerald-300/[0.045] p-5"><LockKeyhole className="size-5 text-emerald-300" /><p className="mt-3 text-sm font-semibold text-white">Default-safe access</p><p className="mt-2 text-xs leading-5 text-slate-400">New grants are explicit. No collection is public by implication.</p></div></div>
      <section className="mt-5 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{workspace.isLoading ? <div className="col-span-full flex min-h-40 items-center justify-center gap-2 text-sm text-slate-500"><Loader2 className="size-4 animate-spin text-cyan-300" /> Loading collection scope</div> : collections.map((collection) => <article key={collection.id} className="nexus-glow-panel rounded-3xl p-5"><div className="flex items-start justify-between"><div className="grid size-10 place-items-center rounded-xl border border-cyan-300/10 bg-cyan-300/[0.05]"><FolderKanban className="size-5 text-cyan-300" /></div><span className="rounded-full border border-white/8 px-2 py-1 text-[10px] text-slate-500">{sources.filter((source) => source.collectionId === collection.id && source.status === "indexed").length} indexed</span></div><h2 className="mt-6 text-base font-semibold text-white">{collection.name}</h2><p className="mt-2 min-h-9 text-xs text-slate-500">{collection.description || "No description has been added."}</p><button onClick={() => toast.message("Collection grants are enforced in the organization policy layer.")} className="mt-5 flex items-center gap-1.5 text-xs font-medium text-cyan-200 hover:text-cyan-100"><UsersRound className="size-3.5" /> Configure access</button></article>)}<button onClick={() => setOpen(true)} className="min-h-[220px] rounded-3xl border border-dashed border-white/12 bg-white/[0.015] p-5 text-left transition-colors hover:border-cyan-300/30 hover:bg-cyan-300/[0.03]"><div className="grid size-10 place-items-center rounded-xl border border-white/8 bg-white/[0.03]"><Plus className="size-5 text-slate-400" /></div><p className="mt-6 text-sm font-semibold text-slate-200">Create an isolated collection</p><p className="mt-2 max-w-xs text-xs leading-5 text-slate-500">Separate policy, support, engineering, or customer knowledge before it can be retrieved.</p></button></section>
    </div>
  );
}
